# Question 1

In [1]:
import numpy as np
def compute_vector_length(vector):
    # len_of_vector = np.linalg.norm(vector)
    len_of_vector = np.sqrt(np.sum(np.square(vector)))
    return len_of_vector

vector = np.array([-2, 4, 9, 21])
result = compute_vector_length([vector])
print(round(result, 2))


23.28


# Question 2

In [2]:
def compute_dot_product(vector1, vector2):
    # result = np.dot(vector1, vector2)
    result = np.sum(vector1 * vector2)
    return result

v1 = np.array([0, 1, -1, 2])
v2 = np.array([2, 5, 1, 0])
result = compute_dot_product(v1, v2)
print(round(result, 2))

4


# Question 3

In [3]:
x = np.array([[1, 2],
              [3, 4]])
k = np.array([1, 2])
print('result \n', x.dot(k))

result 
 [ 5 11]


# Question 4

In [4]:
x = np.array([[-1, 2],
              [3, -4]])
k = np.array([1, 2])
print('result \n', x@k)


result 
 [ 3 -5]


# Question 5

In [5]:
def matrix_multi_vector(matrix, vector):
    # result = np.matmul(matrix, vector)
    result = np.sum(matrix*vector.T, axis=1)
    return result

m = np.array([[-1, 1, 1], [0, -4, 9]])
v = np.array([0, 2, 1])
result = matrix_multi_vector(m, v)
print(result)

[3 1]


# Question 6

In [6]:
def matrix_multi_matrix(matrix1, matrix2):
    # result = np.matmul(matrix1, matrix2)
    result = np.zeros((matrix1.shape[0], matrix2.shape[1]))
    for i in range(result.shape[0]):
        result[i] = matrix_multi_vector(matrix2.T, matrix1[i])
    return result

m1 = np.array([[0, 1, 2], [2, -3, 1]])
m2 = np.array([[1, -3], [6, 1], [0, -1]])
result = matrix_multi_matrix(m1, m2)
print(result)

[[  6.  -1.]
 [-16. -10.]]


# Question 7

In [9]:
m1 = np.eye(3)
m2 = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
result = m1 @ m2
print(result)

[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


# Question 8

In [10]:
m1 = np.eye(2)
m1 = np.reshape(m1, (-1, 4))[0]
m2 = np.array([[1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3], [4, 4, 4, 4]])
result = m1 @ m2
print(result)

[5. 5. 5. 5.]


# Question 9

In [11]:
m1 = np.array([[1, 2], [3, 4]])
m1 = np.reshape(m1, (-1, 4), "F")[0]
m2 = np.array([[1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3], [4, 4, 4, 4]])
result = m1 @ m2
print(result)

[29 29 29 29]


# Question 10

In [12]:
def inverse_matrix(matrix):
    # result = np.linalg.inv(matrix)
    a, b, c, d = matrix.flatten()
    det = a*d - b*c
    try:
        result = np.array([[d, -b], [-c, a]]) / det
    except ZeroDivisionError:
        result = None
    return result

m1 = np.array([[-2, 6], [8, -4]])
result = inverse_matrix(m1)
print(result)

[[0.1  0.15]
 [0.2  0.05]]


# Question 11

In [13]:
def compute_eigenvalue_eigenvectors(A):
    eigvals, eigvecs = np.linalg.eig(A)
    return eigvals, eigvecs

matrix = np.array([[0.9, 0.2], [0.1, 0.8]])
eigenvalues, eigenvectors = compute_eigenvalue_eigenvectors(matrix)
print(eigenvectors)

[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


# Question 12

In [14]:
def compute_cosine(x, y):
    dot_product = np.dot(x, y)
    norm_x = np.linalg.norm(x)
    norm_y = np.linalg.norm(y)
    cos_sim = dot_product / (norm_x * norm_y)
    return cos_sim

x = np.array([1, 2, 3, 4])
y = np.array([1, 0, 3, 0])
result = compute_cosine(x, y)
print(round(result, 3))

0.577
